apiVersion: v1
kind: Service
metadata:
  name: gittrend-web
spec:
  type: LoadBalancer
  selector:
    app: gittrend-web
  ports:
  - port: 5009
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gittrend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gittrend-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gittrend-web
    spec:
      containers:
      - name: gittrend-web
        image: chrwalte/gittrend:1.0.26
        ports:
        - containerPort: 80
